---
all:
  vars:
    ansible_ssh_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@158.160.66.105 -i {{ ansible_ssh_private_key_file }}"'
    become: true
    ansible_python_interpreter: /usr/bin/python3


  hosts:
    master-1:
      ansible_host: 10.0.10.31
      ip: 10.0.10.31
      access_ip: 10.0.10.31
    worker-1:
      ansible_host: 10.0.10.25
      ip: 10.0.10.25
      access_ip: 10.0.10.25
    worker-2:
      ansible_host: 10.0.20.27
      ip: 10.0.20.27
      access_ip: 10.0.20.27
    worker-3:
      ansible_host: 10.0.30.9
      ip: 10.0.30.9
      access_ip: 10.0.30.9
  children:
    kube_control_plane:
      hosts:
        master-1:
    kube_node:
      hosts:
        worker-1:
        worker-2:
        worker-3:
    etcd:
      hosts:
        master-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
