---
- name: Prepare to install k8s
  ansible.builtin.import_playbook: prepare.yml
 
- name: Install K8S
  ansible.builtin.import_playbook: kubespray/cluster.yml

- name: Copy config k8s
  ansible.builtin.import_playbook: finish-k8s.yml

- name: Install grafana
  ansible.builtin.import_playbook: monitoring.yml

- name: Deployment app
  ansible.builtin.import_playbook: deploy-app.yml
